### ISSUE TITLE
Strange Crash with Draconic Evolution

### ISSUE THREAD

**Issue by Thiana** [hilburn/StevesAddons#12]
Modpack: FTB Inifinity 1.20

Mods Involved:
- Steve's Addon's 0.8.3
- Steve's Factory Manager A93
- Draconic Evolution 1.01-snapshot4

Procedure:
Place down a Manager, create an Input in SFM, then try to set the items. As soon as you type anything into the search box the game crashes.

The odd part is that even if you disable Draconic Evolution, the crash continues *for that world*. So if you start a new world, there is no crash until you load that world with DE enabled.

Nothing in the stack trace points to a problem with Draconic Evolution's code so I'm opening the issue here.

Logs:
1 -- http://paste.ee/p/Fp9ua -- Log with Draconic Evolution enabled.
2 -- http://paste.ee/p/e3koL -- Log without DE enabled.

Thanks.

**Comment by hilburn** [comment]
Could you try it without Steve's Addons? The crash appears to be occurring in "vanilla" SFM code

That said, I am running fine in Infinity 1.10 with DE 1.01-Snapshot3, and the same SA and SFM versions so I think that while it's SFM causing the crash, it's DE doing something squiffy. Regardless, I'll try to hunt it down and see if I can fix it via SA

**Comment by hilburn** [comment]
Ok - so a bit of an update. I loaded Snapshot-4 into my dev environment to go bug hunting

It's a fairly minimalist set of mods as I normally just load things in as and when I need to check things (having a 5-10 minute load gets really old, really fast when you are constantly reloading the environment)

Full List:

NEI 1.0.3.62
CCC 1.0.4.29
SFM A93
CoFHCore 3.0.0B9
SA 0.8.3
TF RC1.0.0RC1
TE 4.0.0B8
DE 1.0.1-Snapshot4
Forestry 3.4.0.7
JABBA 1.2.0

And with that set of mods I am able to use the search fine with no crashes at all

**Comment by Thiana** [comment]
I just tried it without SA loaded... The world used in the crash logs is still crashing (http://paste.ee/p/ranar), but when I create a new world the bug doesnt show itself. I'll replicate your environment and see if it crashes.

**Comment by Thiana** [comment]
No crash here with just those minimal mods added. I'll add the Inifinity mods in chunks until I get the crash again, try and isolate the exact combination.

**Comment by Thiana** [comment]
It looks like the problem is library related not mod related. Adding all the Infinity mods to the MultiMC created test instance resulted in no crash. But copying the Infinity instance with MMC does result in a crash. The only difference is in json files specifying the libraries to load :(

**Comment by hilburn** [comment]
Okay... That's very weird - does MMC have an issue tracker - because this sounds like it might be one for them!

**Comment by Thiana** [comment]
I think the problem is with the FTB launcher's library setup since if you create a clean instance and install the infinity mods/config it works fine. Its only when you use the imported instance in MMC or run it with FTBLauncher directly that it crashes. Given that the FTB Launcher is due to be phased out in the next 6 months or so I'm guessing whatever the issue is will remain unsolved.

**Comment by hilburn** [comment]
I don't think it's right to blame FTB - as I've run it fine. But it is odd

**Comment by hilburn** [comment]
Just a heads up - this crash is actually due to RFTools not Draconic Evolution: http://www.reddit.com/r/feedthebeast/comments/2xnsbl/psa_rftools_crash_affecting_various_mods/
