### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by RedsaphirCZ** [hilburn/StevesAddons#13]
I don't know why,but sometimes when i delete something it crashes.
Crash log: http://pastebin.com/L60GDqCT

**Comment by hilburn** [comment]
This is on MultiMC - I've been having some reports from MultiMC about not applying my transformers correctly - I will look into it

**Comment by RedsaphirCZ** [comment]
Yes, it is multiMC

**Comment by hilburn** [comment]
@RedsaphirCZ was this on a SSP or a SMP one? 
Could you provide the startup logs? this should help identify if it's a ASM issue

**Comment by hilburn** [comment]
Resolved in v0.9.7 - there was an occasional issue with the transformer not being applied on the serverside due to a typo on my part - let me know if this crops up again but it shouldn't
