### ISSUE TITLE
"tiny suggestion" give saves there own folder

### ISSUE THREAD

**Issue by kurokuno** [hilburn/StevesAddons#15]
just to make the root MC directory on servers a little neater =P  so rather then just in the main folder have a small SFMA-Saves type folder for them all to go into

**Comment by hilburn** [comment]
they do have their own folder: 

![](http://puu.sh/gpWqR/2cee49ee5b.png)

**Comment by kurokuno** [comment]
thats really odd on my creeper server there just dumping out in the /home/minecraft folder loosely o.O really odd

**Comment by hilburn** [comment]
This might have had something to do with #17 - should be resolved
