### ISSUE TITLE
"small suggestion"

### ISSUE THREAD

**Issue by AoKMiKeY** [hilburn/StevesAddons#16]
I know this is not the right place for this but is most likely going to be something you check. I good ability for you to add to steves factory manager would be the ability to copy a node stem. By this i mean you will be able to click on the stem of inputs, outputs, etc and it would just copy them. So basically a copy and paste feature. Also the system would also be able to copy the groups ( i think thats what they are called ). by this i mean the things that hold nodes with in them so you can have embedded code. 

Just a small suggestion.

**Comment by hilburn** [comment]
That's what the copy button is for, just drag the group onto it
