### ISSUE TITLE
Save command does not honor slashes on Linux

### ISSUE THREAD

**Issue by zeryl** [hilburn/StevesAddons#17]
Created a Manager Duplicator, then did /stevesaddons save.  The filename it created is:

world\managers\zeryl.nbt

In the root of the server structure.  Should have used / instead of \\ in this instance.

**Comment by hilburn** [comment]
Ok, this is fixed
I'm working on something new at the moment so the codebase is a bit unstable (should have branched) and I can't make a new build for you right now - but hopefully by the weekend there will be something up on Curse

**Comment by zeryl** [comment]
No need for a new build for me, I can easily create/move the files, just figured it better for others :)

**Comment by hilburn** [comment]
Should be fixed in the 0.9.X builds
