### ISSUE TITLE
dedicated server crash  0.9.8

### ISSUE THREAD

**Issue by nebularazer** [hilburn/StevesAddons#20]
Hi, i got a crash with my dedicated server on startup.
Works in Singleplayer.

Forge: 10.13.2.1340 (also crashes with 1291)
StevesFactoryManager: A93
StevesAddons: 0.9.8 (works with 0.9.7)

[FML-Log](https://gist.github.com/nebularazer/42d1397db23952d86540)
[Crash-Log](https://gist.github.com/nebularazer/67e23981b579227ed4a3)

**Comment by gazpachoking** [comment]
Having the same issue on a dedicated server.

**Comment by hilburn** [comment]
Thanks for bringing this to my attention - minor typo while I was tidying stuff up... Fixed in 0.9.9 and should be on CF shortly
