### ISSUE TITLE
item missing

### ISSUE THREAD

**Issue by jameseck** [hilburn/StevesAddons#21]
Hi,

I'm using Steve's Addons v0.9.7 and am unable to find the EnderIO Silicon item in any of the inputs/outputs/conditions.

This was not an issue in the previous version I was using (0.7.something).  I updated because of random crashes when searching for items.  This issue is mostly fixed now, but has introduced this other issue.  I know this issue wasn't apparent then, because I have another manager which is processing Silicon and the item is still selected in an input and output.

I'm running a customised pack, based on the FTB Infinity pack.

I also tried 0.9.8, but the server crashes almost instantly as per another issue reported here (still open).

Thanks

J

**Comment by hilburn** [comment]
Just tested - cannot reproduce

![](http://puu.sh/gKVHf/f0c9d6b908.png)

**Comment by jameseck** [comment]
Hi,

I'm not sure what more information I can provide about this, but it's
definitely a problem for me.

When I search for "silicon", I see a bunch of items with silicon in the
name, but not the EnderIO silicon.
There is one item which is exactly called "Silicon" from ProjectRed.
Is it possible that this is causing the other silicon to not show up, due
to the name being the same?

[image: Inline images 1]

**Comment by jameseck** [comment]
![2015-03-22_15 54 53](https://cloud.githubusercontent.com/assets/5069969/6770064/26f7f7ea-d0ac-11e4-987c-aa5ab96ccba6.png)

**Comment by hilburn** [comment]
Ender io does not add silicon if another silicon already exists iirc. Either way - the search is functioning correctly

**Comment by hilburn** [comment]
try v0.9.10 - on CF shortly

**Comment by jameseck** [comment]
Fantastic, it works :)
Thanks for the quick resolution and for providing the mod in the first place - very useful!
