### ISSUE TITLE
Variable selection crash.

### ISSUE THREAD

**Issue by Yusunoha** [hilburn/StevesAddons#26]
I'm trying to select a block in a variable, but as soon as I enter the containers window I crash. this doesn't seem to happen when I select a block through the other container options, only with variable.

here's a few pastebins of the same crash...
http://pastebin.com/vuLMKYMR
http://pastebin.com/q41kR0mm
http://pastebin.com/xn8sUz3L
http://pastebin.com/rrjhz5Zx
http://pastebin.com/YhL42vXY

the mod version is 0.9.11 from the Infinity modpack, version 1.3.4

**Comment by AoKMiKeY** [comment]
Pretty sure that is a old version: http://www.curse.com/mc-mods/minecraft/226067-steves-addons#t1:other-downloads

Try updating to the newest.

**Comment by Yusunoha** [comment]
indeed, with version 0.9.13 I no longer seem to crash, mistake on my part for not trying a newer version first.
I'll report this bug to on the FTB forum and I'll recommend them to update the mod to the newer version.

**Comment by hilburn** [comment]
urgh - i'm an idiot for not checking the version number, spent like 20 mins trying to reproduce this error last night

cheers @AoKMiKeY for pointing that out

**Comment by AoKMiKeY** [comment]
No problem. always happy to help.
