### ISSUE TITLE
De-selecting variable type bug

### ISSUE THREAD

**Issue by PiggyWhiskey** [hilburn/StevesAddons#27]
De-selecting SA's container types for a variable deselects the top type as well (Inventory/Tank)
Infinity :1.3.4
SA :0.9.11
SFM :A93

RF Receiver -> Inventory
RF Storage -> Tank

**Comment by AoKMiKeY** [comment]
Copy and paste from last time :P
"Pretty sure that is a old version: http://www.curse.com/mc-mods/minecraft/226067-steves-addons#t1:other-downloads"

Try updating to the newest version and see if it works :)

**Comment by PiggyWhiskey** [comment]
Bugger, sorry about that. Infinity just updated, falsely assumed they used the most recent of all the mods.

**Comment by AoKMiKeY** [comment]
Mod packs take a long time to update so when they go though the submission process everything is tested with what ever version that was submitted to be used. Common problem. If you see a bug just do a quick check to see if it the most recent version of the mod and if its not just update it yourself :)

**Comment by hilburn** [comment]
Interesting... I'll look into this (can confirm it's still an issue)

**Comment by hilburn** [comment]
Hehe you found a really subtle issue @PiggyWhiskey - in the name of optimization VSWE was only giving the data transfer 3 bits (0-7) so 8 and 9, the two that caused issues, were overflowing back to 0 and 1.
