### ISSUE TITLE
Somewhat crash from copy

### ISSUE THREAD

**Issue by OldOpa** [hilburn/StevesAddons#29]
The game somewhat crashes if you try to copy a cammand with multiple groups that contain something. "Somewhat crashes" because it goes back to the title screen of minecraft and you then can continue without the command being copied.

**Comment by hilburn** [comment]
Gonna have to see console logs at the very least as I have not had any trouble with doing this in testing

**Comment by OldOpa** [comment]
This is printed if i try to copy the command:

[Player] joined the game
[18:41:13] [Server thread/INFO]: [Player] lost connection: TextComponent{text='A fatal error has occured, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:41:13] [Server thread/INFO]: [Player] left the game
[18:41:13] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:41:13] [Server thread/INFO]: Stopping server
[18:41:13] [Server thread/INFO]: Saving players

You need to play with it. It seems to appear randomly and changing only small things can crash:

![2015-04-06 19_11_04-](https://cloud.githubusercontent.com/assets/10256143/7008294/6dcc934c-dc91-11e4-89da-106a4c593011.png)

Changing the line from the second condition let it crash. Once it appeared on the true and once it appeared on the false end of the condition. It seems weird and I can't draw a connection why it crashes. Maybe it is the fault of SFM but it is not updated anymore.

**Comment by hilburn** [comment]
Ok - so the problem is likely caused by the fact that you are hitting the Command limit (511) when you try to copy this lot - however I have spent the last 15 minutes trying to duplicate this error and have not managed to do so

"You need to play with it" is not useful for reproducing the error - unless you can tell me how to reliably generate the error there is nothing I can do

**Comment by OldOpa** [comment]
Well, I played with it and I think it hasn't to do with the limit, it will simply cut off the copy at a given command. But as I don't know how you can reproduce or what causes the "crash" I will close this and keep it by: You are aware of this and maybe there will be a fix sometime.

Thanks for your time and I appologize if I wasted it, but the problem caused to be more difficult than I expected.
