### ISSUE TITLE
Fatal Crash - Copying a command group

### ISSUE THREAD

**Issue by Tim020** [hilburn/StevesAddons#30]
I got a fatal NPE when copying a command group.
Only crashes the client; but not error log produced
Error here (taken from FTB Log): http://pastebin.com/WratCHFG 
Running the 1.7.10 DW20 pack V 1.2.1

**Comment by hilburn** [comment]
Interesting... are you hitting the command limit on the manager (512 commands) when you are performing this copy?

**Comment by Tim020** [comment]
Nope, had about 7 commands in the group, and at the time I had about 8 or 9 groups, so a total of 63 commands max
