### ISSUE TITLE
Energistics Connector not showing in Factory Manager

### ISSUE THREAD

**Issue by MRuth** [hilburn/StevesAddons#34]
I can't seem to get the Factory Manager to recognize the input/output from the Energistics connector.

![2015-04-08_13 42 45](https://cloud.githubusercontent.com/assets/3927478/7052598/41326c48-ddf5-11e4-87cc-2ca3ed7117d9.png)
![2015-04-08_13 43 01](https://cloud.githubusercontent.com/assets/3927478/7052599/413410f2-ddf5-11e4-8f62-f2e0504d6116.png)
![2015-04-08_13 42 38](https://cloud.githubusercontent.com/assets/3927478/7052600/41350c78-ddf5-11e4-9ae3-7d9790f6aa45.png)

**Comment by hilburn** [comment]
Does it show up in the fluid one?

**Comment by MRuth** [comment]
Yes.
![2015-04-08_14 05 35](https://cloud.githubusercontent.com/assets/3927478/7053092/5d5e5fbe-ddf8-11e4-8180-fd26d00e119f.png)

**Comment by hilburn** [comment]
Fixed - 0.10.1 will be on CF shortly

**Comment by MRuth** [comment]
Thanks!!
