### ISSUE TITLE
RF Node Issues

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#40]
They are very bizarre =). I could not get it to work with Ender IO conduits on the input, but they did work fine on the output as long as they were set to extract. Otherwise the power would back flow in to the output node. The input only worked with a conduit/TD Duct combo.

Some thoughts on improvements. What if the nodes worked more like an RF storage for input and output (tanks)? The Input could hold X amount of RF and the output holds X amount of RF. The default would be to transfer all stored power from the Input to the Output on a trigger. You could also set a limit on the RF transfer from the Input to the Output, they could both have a filter for say 1kRF up to whatever. That way if you have multiple outputs, each one would get 1kRF per trigger or whatever you specify. As long as the input has enough RF being input.

**Comment by hilburn** [comment]
EnderIO has very strange ideas about RF and what it should and shouldn't do (eg. trying to extract power from a capacitor bank is a complete no-no). As such it creates a number of issues when I try to interact with their things. That said, I am working on changes to RF nodes currently so you should see improvements soon.
