### ISSUE TITLE
Server crashing randomly when activating Factory manager

### ISSUE THREAD

**Issue by 9903286** [hilburn/StevesAddons#41]
I don't really know why this happens, but posting it here since this was in the crash log:

> at stevesaddons.asm.StevesHooks.tick(StevesHooks.java:302)
> at stevesaddons.asm.StevesHooks.tickTriggers(StevesHooks.java:292)

This happens randomly when i've got a button set up to trigger the script in a factory manager block.
Crash report: http://pastebin.com/QKC6yrJJ

The script is basically this:
Trigger -> Trigger after 3 seconds -> Move item from container to container -> Emit redstone -> Trigger after 1 second -> Move item from container to container -> End

**Comment by hilburn** [comment]
I'll look into it tonight.. this really shouldn't be happening but it seems to be a weird Java issue I have never seen before
The "Trigger after 1 second" is a delay trigger?

**Comment by 9903286** [comment]
Yup, took a print screen of the inside of the factory manager:
![Factory Manager](https://www.dropbox.com/s/33bf3yleu1fqgh2/manager.png?dl=0)

**Comment by hilburn** [comment]
ok then - think I know what's going on but how to fix it in way that won't slow things down is something I will have to fiddle with

**Comment by fluffle** [comment]
Hi! I had a crash recently on the line that you added in your fix commit above. I had two delayed triggers configured with the same delay hanging off a 5-way sequential-split flow control, and I am pretty sure it was this that caused the crash. It was a nasty one too, the server crashed on startup and I had to restore from backup. Infinity Evolved, Expert Mode, 2.3.5.

[crash-2016-02-28_20.52.23-server.txt](https://github.com/hilburn/StevesAddons/files/151567/crash-2016-02-28_20.52.23-server.txt)
