### ISSUE TITLE
[Crash] Server - When moving RF with RFNode

### ISSUE THREAD

**Issue by marduvGitHub** [hilburn/StevesAddons#43]
Hi
When I did move RF from a RFNode to some Machines connected to factory cable the Server did crash :-(
Se Pastbin: http://pastebin.com/1uMjmPmp <--- Updated 17.04.2015

Let me know if there is something you want me to do.

**Comment by hilburn** [comment]
full crash log please- can you confirm that you are running on the latest version?

**Comment by marduvGitHub** [comment]
@hilburn Her you go: http://pastebin.com/1uMjmPmp
Yes this did happen when running the latest version 0.10.2

I did use multiple triggers to draw more RF from the RFNode and join them together to get more RF to the machine.
This did not crash at once, but took a little time before this happened.
My solution was to remove the mod briefly to remove the "code" and items.

**Comment by hilburn** [comment]
I see - explains why weirdness was happening. Firstly the RFNode is kinda glitchy at the moment - and also that's a really weird way of doing it... I'll look into it though

**Comment by marduvGitHub** [comment]
I se...
Yes I know but the RF output was so lo so I did try that to boost the amount and that did work for awhile :-)

**Comment by hilburn** [comment]
Should be fixed in 0.10.4
