### ISSUE TITLE
Moving program between worlds changes items in commands

### ISSUE THREAD

**Issue by Rodg88** [hilburn/StevesAddons#44]
I did a /stevesaddons save in one world, and moved the .nbt file to a new world and loaded it into a new manager, and the items I'd selected in filters/crafters in the program had changed (except vanilla items). I guess it's using the item id numbers instead of the unique name for items.

**Comment by hilburn** [comment]
Between worlds it should be the same provided the modpack doesn't change (and both worlds have always been on the same pack, creating a world, then removing a mod from the pack, then creating a second world will create issues i think) - it doesn't save the name as that's not how the manager saves it - so would be very difficult to convert to the unlocalized name for storage, especially as there is no real way to inspect the NBT map.

I may look into this in the future - but as it works perfectly in about 95% of cases, and works mostly in the other 5% it's kind of low priority right now

**Comment by Rodg88** [comment]
Ah ok, the modpack had updated between starting my first world and making the new world. So that's fine.
