### ISSUE TITLE
Crafting Bug /w AE2

### ISSUE THREAD

**Issue by SecretSnake55** [hilburn/StevesAddons#48]
No Crash logs
Tested with 2 chest 1 input and 1 output
trying to craft seeds  1 sand and 1 quartz dust = 2 quartz seed

but all it will do is move the sand and quartz dust from 1 chest to the other skipping the crafting!

Hope this helps  hilburn

Edit I can make a small youtube vid if you need me too!!

**Comment by way2muchnoise** [comment]
@SecretSnake55 Try setting an quartz seed white list on the output chest

**Comment by SecretSnake55** [comment]
did that and every thing i could from fuzzy to match all 
and if i white list the seed for the output nothing comes out! 
it is like the crafting part is just skipped!

**Comment by hilburn** [comment]
ok - fixed
going to see if i can fix the SFM bug that's keeping it out of AS2 but i'll push a release later today

**Comment by SecretSnake55** [comment]
cool thanks @hilburn

**Comment by hilburn** [comment]
not really anything to follow at the moment - i should hopefully have an early release sometime next week
