### ISSUE TITLE
Server crash when deleting last item in group or a full group

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#49]
http://paste.ubuntu.com/10889638/

**Comment by hilburn** [comment]
you are going to have to provide more information that this on how to reproduce this - i've deleted groups nested over 30 deep in testing and never had an issue with this

**Comment by tgstyle** [comment]
I tested this nested group 3 deep.

![2015-04-25_14 23 25](https://cloud.githubusercontent.com/assets/5832709/7334682/531d7f96-eb57-11e4-9c16-a5028c2076e9.png)

I have them named here with inputs and outputs.
![2015-04-25_14 26 26](https://cloud.githubusercontent.com/assets/5832709/7334689/705c06ae-eb57-11e4-9c4b-8b5264f3ff21.png)

Triggers and nodes.
![2015-04-25_14 26 30](https://cloud.githubusercontent.com/assets/5832709/7334692/78539db8-eb57-11e4-8b23-1e3ab2d671f8.png)

The odd thing in this test is if I delete it from the top, it deletes fine. If I delete the Group 1S/2S it crashes. Also the odd thing is the connections are not showing even though they are there.

**Comment by hilburn** [comment]
Thank you very much for this - finally a reproducable setup
I believe 0.10.7 should fix this issue for you, please let me know if it doesn't
