### ISSUE TITLE
Duplicator not saving in SMP

### ISSUE THREAD

**Issue by ChaosNicro** [hilburn/StevesAddons#5]
I am trying to use a duplicator on a server.
When I shift+right-click to save the program, it receives the enchantment glow as normal.
When I then open my inventory it loses the glow and shows no coordinates.
carrying it through the world it frequently loses and gains the glow repeatedly.
Additionally using it on any block will temporarely restore the glow.
The duplicator is at no point in time linked to anything and does not work on any managers.
It can not be reset to normal once bugged.
In singleplayer everything works fine.
When originally trying this, I switched dimensions with the duplicator in my inventory though this does not seem to make a difference.
I am using version 0.7.0 of the mod, aswell as all the mods in the Hermitcraft Modsauce pack. 
SFM is version A93.

**Comment by hilburn** [comment]
Ah ok, the whole thing is built against A92 so I cannot say for sure it will work for 93.. I'll probably need to do some work updating it

**Comment by hilburn** [comment]
@ChaosNicro could you provide a download link for A93 - can't find it

**Comment by ChaosNicro** [comment]
Strange, I can't either.
I downloaded A93 as part of the "Hermitcraft Modsauce" pack on the ATLauncher, so that is probably your best bet. :S

**Comment by ChaosNicro** [comment]
I could give you my file, but I'm not sure about the redistribution legal stuff

**Comment by hilburn** [comment]
I'll scrub the link after i've downloaded it

**Comment by ChaosNicro** [comment]
http://www.filedropper.com/stevesfactorymanagera93

leave me a message when you're done so I can invalidate that link.

**Comment by hilburn** [comment]
ok, cheers... deleted the comment for you

**Comment by esotericist** [comment]
In case it's necessary for the future:
https://twitter.com/Steves_Carts/status/538848883552825344
vswe gave a public download link for A93 here.

**Comment by hilburn** [comment]
Ok I just did some tests and it seems to work fine with A93 - might be some other mod affecting it in the pack or it's a server/client desync issue - ChaosNicro are you playing on a server?

**Comment by ChaosNicro** [comment]
As the title suggests yes, and as it also sais the mods are in a pack named "Hermitcraft modsauce" available on the ATLauncher.

**Comment by hilburn** [comment]
I have not been able to duplicate this behaviour on a SMP server, and I'm afraid I do not have the time to discover which out of 158 mods are causing the issue.

I test with a pack of 62 commonly used mods and it works fine in both MP and SP instances - so unless I can get some more details about how to reliably reproduce I'm gonna have to shuffle this to low priority

**Comment by ChaosNicro** [comment]
Thats entirely ok, just forget about it if you want.
