### ISSUE TITLE
AE Connector not connecting

### ISSUE THREAD

**Issue by agentrenamon** [hilburn/StevesAddons#50]
I can't use the Energistics Connector, since it always auto-breaks whenever it touches anything that's part of the AE2 mod. The StevesAddon config file is set: "B:applied_energistics_2=true", and nothing else seems to be malfuntioning (the duplicator made moving my auto-compressor rig insanely simple)! I'm using AE2 version rv2-beta-7, and Steve's Factory Manager A93.

Please Help; I need the Connector to work in order to make a certain farming build a reality.

**Comment by hilburn** [comment]
can you check your security settings on the AE network?

**Comment by agentrenamon** [comment]
Blank Card in it, on a single-player map. I also tried with a card set for all permissions possible, just to test; but I got the same result. It connects fine to any AE2 cables/ blocks not currently linked to a network; but the moment it becomes linked to one, POP! It acts like it was mined. REALLY hoping this is just a bug.

BTW, in case it's something weird, also have loaded the following AE2-related addons:
- Extra Cells 2.2.67
- Thaumic Energistics 0.8.8.1b-rv2 (cool mod, if you haven't seen it!)

**Comment by hilburn** [comment]
Well I build against AE2-rv2-beta-22 and it works fine there. Try removing the security system entirely and see if that works

**Comment by tgstyle** [comment]
I had to use a blank card with build permissions enabled in order for it to work. Any way to make it part of the ME Security without that?

**Comment by agentrenamon** [comment]
tgstyle is right; I did the same thing, and now it works fine! Maybe the Connector is a bit fickle about Security Settings or something....

**Comment by hilburn** [comment]
AE is a bit fickle about security settings
As for the crash - Try with AE2-beta-22, if you still get the crash report it on their github

**Comment by way2muchnoise** [comment]
@agentrenamon AE-devs changed the AEItemStack.create() from taking an Object to taking an ItemStack and since we compile against the ItemStack it can't find that method.
Just updating to a more recent beta will fix it. Something rv2-beta-22 or higher will do.

**Comment by agentrenamon** [comment]
Update to beta 22; and now i'm having a no-win fight with Thaumic Energistics... I hate my life sometime...

**Comment by hilburn** [comment]
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2233359

**Comment by agentrenamon** [comment]
Found a good work-around for my AE project: Turns out that the Factory Manager recognizes the AE2 Network Interface as a valid inventory to Input from and Output to. This means I can sort out issues at my leisure.
