### ISSUE TITLE
Energistics Connector Crash

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#51]
https://gist.github.com/anonymous/785d795c0afd82574d7d

This happened when I had auto-crafting commands coming out of the Energistics Connector and back in,

**Comment by NewGalaxyCraft** [comment]
Can confirm, everytime you import something in your AE² Network through the energistics connector, client will crash or server will shutdown. Using Version 0.10.7

**Comment by hilburn** [comment]
What version of AE are you using? they changed the API and it is not backwards compatible

**Comment by NewGalaxyCraft** [comment]
Its the rv2-beta-18 of Applied Energistics in the Infinity Modpack version 1.5.0

**Comment by hilburn** [comment]
update to 0.10.8 ad see if it still occurs - if it does then open up a new issue with the appropriate crash log
