### ISSUE TITLE
Crash deleting output

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#53]
https://gist.github.com/tgstyle/2007906da22eaaee5a7c

I was in a group and just trying to delete a single output. Seems to happen quite frequently.

**Comment by hilburn** [comment]
Ok you have reported a number of bugs now and every single time have failed to give me information such as version number, modpack etc - every single time that is my first question. I'm going to close this issue and ignore it until you open an issue with the information i need to have even a hope in hell of identifying the issue

**Comment by tgstyle** [comment]
Well first things first. I always use the latest version of the mod before I report anything. So you can always assume that.

**Comment by tgstyle** [comment]
Otherwise I am not sure what else you would like me to report other then the version of the mod. It is not like SFM is updating any time soon, as to why you are rewriting it as ASM =).

**Comment by hilburn** [comment]
Please state it regardless

Sever or single player? how reproducible is it? 100% of the time? 10%? 1%?
