### ISSUE TITLE
Re-Report Crash Deleting Output

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#54]
For your prima donna attitude referring to issue https://github.com/hilburn/StevesAddons/issues/53

https://gist.github.com/tgstyle/2007906da22eaaee5a7c

Steves Addons 0.10.8 - note I ALWAYS try the latest version of all error reported and involved mods before I submit a report. This will ALWAYS be the case. I test many mods and always report on the latest versions.

I use a custom modpack and here are the installed mods.
http://paste.ubuntu.com/10988657/

Closing issues as a tyrannical statement will not help your mod progress and will just DETER users from supporting your mod. I am just trying to help make it better for the community as a while supporting your mod. Ever heard of collaboration? Going back and forth to figure it out? Now please lets have some collaboration and make this a better mod in advance and supporting your work on ASM.

Now for why this happens, I am not sure. It is very random, and happens while deleting outputs nested in groups. The only trend I have noticed is the nested group has an output node.

**Comment by hilburn** [comment]
Sever or single player? how reproducible is it? 100% of the time? 10%? 1%?

**Comment by tgstyle** [comment]
Thanks for replying on this one, It is server. It happens probably about 10% of the time, and not on every Output.

**Comment by hilburn** [comment]
Ok - is it a crash on the sever or client?

**Comment by tgstyle** [comment]
Server crashes to a complete stop and needs to be restarted.

**Comment by tgstyle** [comment]
Here are some screens, the one that crashes upon deletion is the one that is open a few shots down.
![2015-05-05_01 44 27](https://cloud.githubusercontent.com/assets/5832709/7468960/a5b22e48-f2cb-11e4-8481-abdebdb1a8cb.png)
![2015-05-05_02 05 22](https://cloud.githubusercontent.com/assets/5832709/7468962/a93f70ca-f2cb-11e4-85e7-1a0ec644913e.png)
![2015-05-05_02 05 24](https://cloud.githubusercontent.com/assets/5832709/7468964/ace8908a-f2cb-11e4-9e74-cba05577cfd0.png)
![2015-05-05_02 05 26](https://cloud.githubusercontent.com/assets/5832709/7468968/af8774e6-f2cb-11e4-99b6-000dc2573352.png)
![2015-05-05_02 05 16](https://cloud.githubusercontent.com/assets/5832709/7468969/b1913114-f2cb-11e4-8a6d-83f86681441a.png)

If I restart the server, re-create that output and delete it, it no longer crashes. If I copy that output, delete it, let it crash, restart and replace it with the copy, it no longer crashes if I delete the copy. It is very bizarre. The only thing I can think that may be related, is i shift-clicked to overwrite the manager once, and I had to go through and fix all the inventories. After that, it had the crashing issue upon deletion.

**Comment by hilburn** [comment]
Should be fixed in 0.10.11 - spent half an hour adding and deleting stuff, copying with the duplicator and the GUI button and had no issues

**Comment by tgstyle** [comment]
Awesome, thank you. I will try it and report back if I see any more issues.

**Comment by tgstyle** [comment]
If I copy the manager to a new manager it works. If I try to overwrite the existing manager then open it, I get this error on the client and it disconnects the client. Any subsequent attempt to access the manager results in this error and a disconnect.

https://gist.github.com/tgstyle/44a157432a6015126942

**Comment by hilburn** [comment]
hmmm right, well that aint good... is that just when you overwrite an existing manager, or when you add to n existing manager as well?

**Comment by tgstyle** [comment]
I can confirm it happens for both.

**Comment by hilburn** [comment]
Ok - well I'm just going to disable the enhanced deleting for now as it is just causing me far too much of a headache

**Comment by tgstyle** [comment]
Whatever works. I am looking forward to ASM, hopefully it won't be as much of a headache.

**Comment by hilburn** [comment]
Works fine in ASM - but I wrote it to be a lot less faff in the first place
