### ISSUE TITLE
Feature Request: Increase maximum items number

### ISSUE THREAD

**Issue by Keridos** [hilburn/StevesAddons#55]
Can you please add in functionality so we can set higher amounts of quantities (bigger than 999) to make this a bit better usable with barrels or deep storage units. Thanks you for creating this mod though, it makes steves factory manager even more awesome.

**Comment by hilburn** [comment]
Not possible. Sorry

**Comment by Keridos** [comment]
What is ASM?

**Comment by hilburn** [comment]
https://github.com/hilburn/AdvancedSystemsManager
