### ISSUE TITLE
Crash using Energistics Connector, specified auto-crafter output amount

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#57]
I created a an Auto-Crafter utilizing an Energistics Connector for IO, and on the output I specified an amount that I wanted it to create per trigger. This is the resulting crash.

SA - 0.10.8

https://gist.github.com/tgstyle/025f616dc667c79766b7

**Comment by hilburn** [comment]
AE version?

**Comment by tgstyle** [comment]
Latest rv2 stable.

**Comment by hilburn** [comment]
fixed in 0.10.9 - it doesn't respect the limited amount as that requires a much bigger bit of rewriting but it won't crash on you
