### ISSUE TITLE
Cant load Pastebin on Server

### ISSUE THREAD

**Issue by Elvarion** [hilburn/StevesAddons#58]
StevesFactoryManagerA93
StevesAddons-1.7.10-0.10.8

When typing /stevesaddon and pressing TAB the server crashes.
Typing /stevesaddon pastebin get xxx (xxx being your pastebin) generates error message.

Error message
http://pastebin.com/n1cgJdtE

**Comment by hilburn** [comment]
Yes - those commands are player-only commands as you need to be holding a duplicator to make it work. That said - server crashing is bad - I will try to fix that, do you have that crashlog?

**Comment by Elvarion** [comment]
Aye, Here it is :)
http://pastebin.com/AZtMdNVs

**Comment by hilburn** [comment]
fixed in v0.10.9
