### ISSUE TITLE
question how i can copy between worlds

### ISSUE THREAD

**Issue by abdullamu** [hilburn/StevesAddons#62]
this mod need wiki of some sort i have steves manager for my ae2 system and i want to copy the code for my new world i have been trying to fine out how since i red it once in change log but whats the command to do that ?

**Comment by way2muchnoise** [comment]
/stevesaddons pastebin put
That will put a link to a paste of the current duplicator disk on your clipboard
then use /stevesaddons pastebin get [LINK] to paste again to a disk

**Comment by hilburn** [comment]
alternatively - /stevesaddons save and /stevesaddons load will save/load to/from a folder which can be more convenient than pastebin
