### ISSUE TITLE
TE Fluids Dupe Bug

### ISSUE THREAD

**Issue by tgstyle** [hilburn/StevesAddons#65]
Latest TE 4.0.1-182
Latest SA 0.10.12
Latest EC2 2.2.71b123
Latest AE RV2-stable 3

Fluid input - magma crucible, fluid output - Energistics connector. Results in infinite fluid from the magma crucible, it never depletes the amount inside of it.

**Comment by AoKMiKeY** [comment]
I can't seem to make this happen with my environment. What is that you are doing to get this to happen.

**Comment by tgstyle** [comment]
Just a Manager with a 1 second Trigger, pulling fluid from a Magma Crucible and putting it in to the Energistics connector. The fluid I tested in the Magma Crucible is Resonant Ender.

**Comment by AoKMiKeY** [comment]
It has either been fixed or EC2 fixed it because I am running EC2-2.2.71b124.
This is how i have tried to reproduce the issue.
http://gyazo.com/ea2f47e18ce9d4d88f31265e45b0fcbc

The drive and controller came after it not working with out them. Where your drives full or anything like that when you had this issue?

**Comment by tgstyle** [comment]
It is not fixed, and EC2b124 still does it (AE2RV2 stable 4). My setup is almost the same, it does it whether the crucible is full or not. Are you using the latest forge 1424 (previous versions of forge still have had the issue)?

**Comment by AoKMiKeY** [comment]
My forge is 1408. I can update it and have a look but i can not seem to get it to do what you where doing.

**Comment by tgstyle** [comment]
So I found out how to duplicate it exactly and how to make it work properly, either way there is still a bug =). This is the overall setup I have.
![2015-06-03_20 39 27](https://cloud.githubusercontent.com/assets/5832709/7975933/ac458f34-0a31-11e5-9971-0ef0c2407f56.png)
![2015-06-03_20 39 34](https://cloud.githubusercontent.com/assets/5832709/7975936/b3300d92-0a31-11e5-9ce8-9da2fa5bbbd0.png)
This one may be important to get it to dupe.
![2015-06-03_20 39 37](https://cloud.githubusercontent.com/assets/5832709/7975939/b859f27e-0a31-11e5-9d8d-ceddd9b27950.png)
![2015-06-03_20 39 41](https://cloud.githubusercontent.com/assets/5832709/7975949/cd963364-0a31-11e5-8b52-adf6a9f37515.png)
![2015-06-03_20 39 46](https://cloud.githubusercontent.com/assets/5832709/7975950/d3ccfeb6-0a31-11e5-8e6b-b50877c8af8d.png)

If you just place the magma crucible and put the input to all sides and do no change anything it should produce infinite fluid.
If you place the magma crucible and change it to input on the bottom output on the top it should produce infinite fluid.
If you place the magma crucible and change it to input top output bottom it should work correctly, as well as having output on any other side.

This setup dupes.
![2015-06-03_20 43 27](https://cloud.githubusercontent.com/assets/5832709/7975975/3272ff10-0a32-11e5-94b8-ec3b437487e2.png)
As well as this.
![2015-06-03_20 44 53](https://cloud.githubusercontent.com/assets/5832709/7975977/3a51b046-0a32-11e5-80d1-e9dd42e979e4.png)
