### ISSUE TITLE
[Mod Enhancement]: Code Optimization for both Addons and possibly SFM (if thats possible)

### ISSUE THREAD

**Issue by Lanse505** [hilburn/StevesAddons#67]
I've noticed aswell as been told by alot of the server owners running RR that SFM has a very heavy TPS impact once you start creating multiple inputs and outputs in the same chain. It gets even worse once you add Variables and Conditions to the Program Chains. Maybe look into if its possible to optimize some of the code for SFM/Addons to lessen the impact on server performance.

**Comment by hilburn** [comment]
https://github.com/hilburn/AdvancedSystemsManager
