### ISSUE TITLE
[Mod Suggestion]: Cluster Modifier

### ISSUE THREAD

**Issue by Lanse505** [hilburn/StevesAddons#68]
I haven't messed too much around with Advanced and normal Cable Clusters, however as far as I know you can remove cables from normal cable clusters, so if you accidentally craft too many you just lost extra cable parts :(

Maybe look into adding a Cluster Table for modifiying/adding/removing Cable parts in clusters?

If there is a way to already do this just close this post and call me a derp :P

**Comment by hilburn** [comment]
craft any combined cluster and you will get the component parts back
