### ISSUE TITLE
AE bug: not able to see item in inscriber

### ISSUE THREAD

**Issue by AoKMiKeY** [hilburn/StevesAddons#69]
This is most likely not a SA issue. Its most likely a SFM issue but I was wondering if it would be possible to fix. When you are looking inside a inscriber on the middle slot where a diamond would go SFM can not do a conditional on that side. It can not seem to find the item and there for always defaults to saying it does not exist.

I can also not pull out of that slot. Only put items into it which is the wired part.

**Comment by hilburn** [comment]
This is not even a SFM issue - the Manager is very capable of inserting and extracting from every slot in the inscriber and can check the slots for conditionals.

**Comment by AoKMiKeY** [comment]
Okay, Sorry. This is a issue but it must be AE related because a set up like this
http://gyazo.com/21a2cc880c6bf24592eced6101ecafde
http://gyazo.com/26a0e6545d186573a918e861e9f73ad4
http://gyazo.com/f0fe0120abd785f9868f329a2f11e956

Does not work. it automatically thinks there is nothing in it. Although imputing to that side works completely fine.

**Comment by hilburn** [comment]
In the condition check the top side, not the north side. That slot is not visible from the side

**Comment by AoKMiKeY** [comment]
I can have every side selected and nothing will happen. I sent you the most logical set up that i could do. I have gone though and set up each side on different triggers and it has still not been able to pull the items out.

**Comment by hilburn** [comment]
You can't pull the items out, it is an input slot. This is not a bug

**Comment by AoKMiKeY** [comment]
That was meant as more of an example. Lets say I need to see if there was a Diamond in that slot. I would do a conditional, I would put the Inscriber put its target to the top or the left and then have a input and output. The input would move a press from the top of a chest into the top of the inscriber. The problem here is that if you try to see what is in the middle slot it will always come back and false no matter what side you are using.

**Comment by hilburn** [comment]
Not true - I have done it fine myself, so I suspect there's something else going on here

**Comment by AoKMiKeY** [comment]
Hmm. well i am booting up my test environment that has your ASM mod on there with AE2 so I am going to see what happens

**Comment by AoKMiKeY** [comment]
http://gyazo.com/97e246b7b45249fcf4419f1f04291b67
http://gyazo.com/a4b01fd1a4e54e977a2bc6a7f4bdea8a
http://gyazo.com/82ace5a04cd2510835db81599a4a2a47

Right so armed with the most up to date SFM and SA with AE2 And nothing else added on 1.7.10 I am still unable to do that check. 

I am attempting to say. If there is diamonds in that middle slot ( i have tried it on all sides ) then move the diamonds from one chest to the other. That is all. Very simple. Still not working.

**Comment by hilburn** [comment]
*shrugs*

I suggest you take it up with AE2

**Comment by AoKMiKeY** [comment]
Right so i have had a look and talked to the guys over at AE2 https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1544#issuecomment-109295072

And they are saying that its this that is most likely the problem
