### ISSUE TITLE
Duplicate container types

### ISSUE THREAD

**Issue by shadowfacts** [hilburn/StevesAddons#7]
![2015-02-13_21 50 14](https://cloud.githubusercontent.com/assets/7091588/6198365/63e21978-b3ca-11e4-82a9-5bc0e1bf8d31.png)
I'm pretty sure that RF Storage shouldn't be listed 3 times under Container Types.

**Comment by hilburn** [comment]
Well.. yes and no - they should all be in there, but they shouldn't all be called the same thing
I'll change it to RF Receivers, Providers and Users

**Comment by hilburn** [comment]
fixed in 0.8.0
