### ISSUE TITLE
Dug: Delete bug

### ISSUE THREAD

**Issue by AoKMiKeY** [hilburn/StevesAddons#71]
Okay, I think you know about this but it's really annoying.

http://gyazo.com/eea686a90a31e61b52a01b81aa36f625
http://gyazo.com/c58a08c854b1ebe74b454f48e2f177f7

When you delete a group it will put all of the groups items onto the main page. Really annoying.

**Comment by hilburn** [comment]
it's not a bug - it's the way SFM works
I tried to fix it but it caused crashes due to the messed up way vswe handles packets. It would require too much of a rewrite of his code to do it properly so you'll have to wait for ASM to be out for this

**Comment by AoKMiKeY** [comment]
Okay :)
