### ISSUE TITLE
Energistics Connector crash

### ISSUE THREAD

**Issue by bdew** [hilburn/StevesAddons#72]
You can select an Energistics Connector as the excess inventory for crafting nodes, and it crashes the server.

crash log: https://gist.github.com/bdew/37e81708d3ceb7ff5ff4

**Comment by hilburn** [comment]
I'll fix that - hopefully I'll have some time Sunday evening

**Comment by hilburn** [comment]
Update on CF - 0.10.13, available when the mods wake up
