### ISSUE TITLE
RF Transfer not working at ALL. Am I dumb or is there an issue?

### ISSUE THREAD

**Issue by BillboardEric** [hilburn/StevesAddons#73]
I am starting to get very frustrated. I am trying to use the RF Transfer feature and it won't work at ALL on anything whether it be capacitor bank to machine or capacitor bank to capacitor bank.

Here are 2 pictures
http://i.imgur.com/Y6dHqCi.png
http://i.imgur.com/dASeE3n.png

With that setup no energy is transfering

**Comment by hilburn** [comment]
Capacitor banks do not work - they do not allow RF to be extracted from them and if you are using a relatively up to date version of EnderIO they won't even be shown as a viable input.
