### ISSUE TITLE
Condition can no longer see output slot of (transvector interfaced) AE2 inscriber.

### ISSUE THREAD

**Issue by Gorgok** [hilburn/StevesAddons#74]
Didn't have any issues before with a list/variable inscriber setup before this last update:  - Conditions can now see all visible slots in inventories, preventing weirdness with things like AE2 inscribers

Now the same setup that worked before doesn't. In fact i cannot get it to detect any items in the output slot, even with every side enabled. Even a simpler setup without transvector interfaces cannot detect an output item present. 

Im not even sure what weirdness there was with inscribers, it seemed like as long as you understood their sidedness they worked fine, with the middle slot input only...

Between 14 and 15 the output slot got lost.

**Comment by hilburn** [comment]
Hmm I'll double check this tonight, I may have derped slightly, though I thought I'd checked everything... the reason for the change was that conditions could never check the middle slot of the inscriber for content, no matter what side you selected - and the same in other inventories.

Sorry for breaking your setup, hopefully should be fixed soon

**Comment by hilburn** [comment]
Ok, this is fixed currently - just have some issues with building the bloody thing to let me post it. Hopefully up on CurseForge tonight (6 hours or so)

**Comment by hilburn** [comment]
0.10.16 is available on Curse
