### ISSUE TITLE
[Suggestion] Store items by name instead of ID

### ISSUE THREAD

**Issue by Xiaminou** [hilburn/StevesAddons#76]
I have came across a problem when transferring problems a program from one modpack to the other, items are stored by ID instead of name, which mean you end up having to re-assign everything.

I don't know much about programming so I didn't think much of it at the time, however I just found out that pneumaticraft used to be the same and changed it today. Is there any way that SFM could do the same?

**Comment by hilburn** [comment]
SFM is up to VSWE, Steve's Addons will not be rewriting that handling to support it.

[ASM](https://github.com/hilburn/AdvancedSystemsManager) may well do, the filtering is getting a complete overhaul in the near future
