### ISSUE TITLE
feature suggestion: inter-mod compatibility

### ISSUE THREAD

**Issue by melchisedekko** [hilburn/StevesAddons#77]
Would be great if you could expand the capability  of the manager to correctly inspect the full contents of Barrels, Caches and MFR Deep Storage Units to work also with storage drawers.

Also I don' see the point of being able to inspect correctly the amout of stuff in a DSU, for example, when the maximum amount of items you can specify in a condition is 999; Which is a realy low amount for those tipe of storage solutions. Increasing that number seems to me a realy good improvement, probably not hard to implement.
![esempio](https://cloud.githubusercontent.com/assets/10241980/10100965/c97c68e4-6395-11e5-8eda-a2105cdef5db.jpg)

**Comment by hilburn** [comment]
I'm no longer patching SFM through Steve's Addons - the code is fundamentally too unstable to be messed with excessively and SA is already skirting the border of it. I am rewriting, improving and extending the whole mod over at [AdvancedSystemsManager](https://github.com/hilburn/AdvancedSystemsManager). As an open source mod however you are welcome to try (or find someone else) to make those changes and submit a PR

That said, the 999 thing did always bug me and is one of the things that will be changed in ASM (or maybe I already changed it, can't remember)

Storage Drawers - I may look into the api for adding support into ASM, but it definitely won't be going into SA
