### ISSUE TITLE
the ability to move code across worlds

### ISSUE THREAD

**Issue by kurokuno** [hilburn/StevesAddons#8]
even if just in the format of a named file inside of ether the client or server and renaming a disk loading from that file i have no idea if such a thing is possible with your method but that would be rather amazing

**Comment by hilburn** [comment]
It is somewhat possible and it's something I have been asked quite a lot - if I get a chance I may put this in (likely requiring a file to be copied across, a command and a config setting that sets the permissions required to use the command - anything like pastebin integration would be something else entirely) 
However, it would be roughly equivalent in difficulty to the rest of the mod combined so I am somewhat wary of committing to doing it within a timeframe - it will get done eventually though

**Comment by kurokuno** [comment]
well i would not expect you to put a time frame on such a massive change =P and just the ability to copy over a file would be more than enough paste bin would be way too over the top im just thinking when i build a few hundred page deep command structure and cannot move it say from a test world to my play world its a pain =P

**Comment by hilburn** [comment]
fixed in 0.8.0

**Comment by kurokuno** [comment]
ty ty ty <3
